[package]
name = "prob_d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.3.6"
itertools = "0.9.0"
superslice = "=1.0.0"
num = "=0.2.1"
libm = "=0.2.1"
